services:
  django:
   
    build: ./kedrSite/
    platform: linux/amd64
   
    container_name: djangoapp
   
    restart: always
    
    expose:
      [8000]
   
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
   
    volumes:
      - django_static_volume:/usr/src/app/static
      - django_media_volume:/usr/src/app/media
      - ./kedrSite:/usr/src/app/

    depends_on:
      - postgres

    environment:
      DB_HOST: postgresdb  
      DB_PORT: 5432

    env_file:
      - ./.env

  node:

    build: ./kedr_new

    container_name: reactapp

    restart: always

    ports:
      - 3000:3000

    command: npm start

    depends_on:
      - django
    volumes:
      - ./kedr_new/public/:/usr/src/app/public/
      - ./kedr_new/src/:/usr/src/app/src/


  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 1337:1337
      - 80:80
      - 443:443
    depends_on:
      - django
    volumes:
      - django_static_volume:/home/src/app/static
      - django_media_volume:/home/src/app/media 

  postgres:

      image: postgres:15-alpine
      platform: linux/amd64
      container_name: postgresdb
      ports:
        - 5432:5432

      volumes:
        - postgres_volume:/var/lib/postgresql/data/

      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=1234
        - POSTGRES_DB=django_db
        - POSTGRES_HOST = 88.218.67.221
        - POSTGRES_PORT = 5432

volumes:
    postgres_volume:
    django_static_volume:
    django_media_volume:
