# Generated by Django 4.2.20 on 2025-06-14 06:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Дерево', max_length=100)),
                ('content', models.TextField(null=True)),
                ('picture', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='tree_photos/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('plant_date', models.DateField(default=datetime.date(2000, 9, 9))),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('owner_name', models.CharField(default='', max_length=256)),
                ('dedicated_to', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TreesImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='tree_photos/')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trees.trees', verbose_name='Дерево')),
            ],
        ),
    ]
